import os
from bs4 import BeautifulSoup
import pytest
import sys
import json

from data_fetchers.schools.sfsu import departments

sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))) )

def get_sample_soup():
    sample_path = os.path.join(
        os.path.dirname(__file__),
        '..', '..', '..', '..', 'tests', 'test_samples', 'sfsu', 'terms_test_sample.html'
    )
    with open(sample_path, 'r', encoding='utf-8') as f:
        html = f.read()
    return BeautifulSoup(html, 'html.parser')

def get_reference_data():
    # Expected departments data based on the user's provided output
    return [
        ('A U - All University', 'A U'),
        ('AA S - Asian American Studies', 'AA S'),
        ('ACCT - Accounting', 'ACCT'),
        ('ADM - Apparel Design And Merchandising', 'ADM'),
        ('AFRS - Africana Studies', 'AFRS'),
        ('AIS - American Indian Studies', 'AIS'),
        ('ALI - American Language Institute', 'ALI'),
        ('AMST - American Studies', 'AMST'),
        ('ANTH - Anthropology', 'ANTH'),
        ('ARAB - Arabic', 'ARAB'),
        ('ART - Art', 'ART'),
        ('ARTH - Art History', 'ARTH'),
        ('ASTR - Astronomy', 'ASTR'),
        ('ATHL - Athletics', 'ATHL'),
        ('BECA - Broadcast And Electronic Communication Arts', 'BECA'),
        ('BIOL - Biology', 'BIOL'),
        ('BIOM - Biomedical Laboratory Science', 'BIOM'),
        ('BUS - Business', 'BUS'),
        ('C D - Communicative Disorders', 'C D'),
        ('C J - Criminal Justice Studies', 'C J'),
        ('C W - Creative Writing', 'C W'),
        ('CA - Creative Arts', 'CA'),
        ('CAD - Child And Adolescent Development', 'CAD'),
        ('CE - Continuing Education', 'CE'),
        ('CEEL - Credit By Evaluation For Experiential Learning', 'CEEL'),
        ('CFP - Certified Financial Planning', 'CFP'),
        ('CFS - Consumer And Family Studies', 'CFS'),
        ('CHEM - Chemistry', 'CHEM'),
        ('CHIN - Chinese', 'CHIN'),
        ('CHS - Center For Humanistic Studies', 'CHS'),
        ('CINE - Cinema', 'CINE'),
        ('CLAR - Classical Archaeology', 'CLAR'),
        ('CLAS - Classics', 'CLAS'),
        ('CLS - Clinical Laboratory Science', 'CLS'),
        ('CMX - Comic Studies', 'CMX'),
        ('COMM - Communication Studies', 'COMM'),
        ('COUN - Counseling', 'COUN'),
        ('CP - Construction Practices', 'CP'),
        ('CPEL - Credit for Prior Experiential Learning', 'CPEL'),
        ('CRSM - CourseMatch', 'CRSM'),
        ('CSC - Computer Science', 'CSC'),
        ('CST - Critical Social Thought', 'CST'),
        ('CWL - Comparative World Literature', 'CWL'),
        ('DANC - Dance', 'DANC'),
        ('DES - Design', 'DES'),
        ('DFM - Dietetics And Food Management', 'DFM'),
        ('DM - Digital Media', 'DM'),
        ('DS - Decision Sciences', 'DS'),
        ('E ED - Elementary Education', 'E ED'),
        ('ECON - Economics', 'ECON'),
        ('EDAD - Educational Administration', 'EDAD'),
        ('EDDL - Educational Leadership', 'EDDL'),
        ('EDUC - Education', 'EDUC'),
        ('ENG - English', 'ENG'),
        ('ENGR - Engineering', 'ENGR'),
        ('ENV - Environment', 'ENV'),
        ('ENVS - Environmental Studies', 'ENVS'),
        ('EPP - English For Professional Purposes', 'EPP'),
        ('ERTH - Earth Sciences', 'ERTH'),
        ('ESE - Early Start English', 'ESE'),
        ('ESM - Early Start Math', 'ESM'),
        ('ETHS - Ethnic Studies', 'ETHS'),
        ('EXCO - Experimental College', 'EXCO'),
        ('F L - Foreign Languages', 'F L'),
        ('FCS - Family &amp; Consumer Sciences', 'FCS'),
        ('FILI - Filipino', 'FILI'),
        ('FIN - Finance', 'FIN'),
        ('FR - French', 'FR'),
        ('GEOG - Geography And Environment', 'GEOG'),
        ('GER - German', 'GER'),
        ('GPS - Global Peace Studies', 'GPS'),
        ('GRE - Greek', 'GRE'),
        ('GRN - Gerontology', 'GRN'),
        ('H ED - Health Education', 'H ED'),
        ('HEBR - Hebrew', 'HEBR'),
        ('HH - Holistic Health', 'HH'),
        ('HIST - History', 'HIST'),
        ('HRM - Human Resource Management', 'HRM'),
        ('HSS - Health And Social Sciences', 'HSS'),
        ('HTM - Hospitality And Tourism Management', 'HTM'),
        ('HUM - Humanities', 'HUM'),
        ('I R - International Relations', 'I R'),
        ('IAC - Inter-Arts Center', 'IAC'),
        ('IBUS - International Business', 'IBUS'),
        ('ID - Interior Design', 'ID'),
        ('IDST - Interdisciplinary Studies', 'IDST'),
        ('ISED - Interdisciplinary Studies in Education', 'ISED'),
        ('ISYS - Information Systems', 'ISYS'),
        ('IT - Information Technology', 'IT'),
        ('ITAL - Italian', 'ITAL'),
        ('ITEC - Instructional Technologies', 'ITEC'),
        ('JAPN - Japanese', 'JAPN'),
        ('JOUR - Journalism', 'JOUR'),
        ('JS - Jewish Studies', 'JS'),
        ('KIN - Kinesiology', 'KIN'),
        ('KOR - Korean', 'KOR'),
        ('LABR - Labor Studies', 'LABR'),
        ('LATN - Latin', 'LATN'),
        ('LCA - Liberal &amp; Creative Arts', 'LCA'),
        ('LIB - Library Education', 'LIB'),
        ('LS - Liberal Studies', 'LS'),
        ('LTNS - Latina/o Studies', 'LTNS'),
        ('M S - Museum Studies', 'M S'),
        ('MATH - Mathematics', 'MATH'),
        ('MEIS - Middle East And Islamic Studies', 'MEIS'),
        ('MGMT - Management', 'MGMT'),
        ('MGS - Modern Greek Studies', 'MGS'),
        ('MKTG - Marketing', 'MKTG'),
        ('MLL - Modern Languages &amp; Literatures', 'MLL'),
        ('MRI - Music Recording Industry', 'MRI'),
        ('MSCI - Marine Science', 'MSCI'),
        ('MTGP - Professional Meeting Planning', 'MTGP'),
        ('MULT - Multimedia', 'MULT'),
        ('MUS - Music', 'MUS'),
        ('NURS - Nursing', 'NURS'),
        ('NUTR - Nutrition and Dietetics', 'NUTR'),
        ('P A - Public Administration', 'P A'),
        ('PCS - Professional Communication Skills', 'PCS'),
        ('PH - Public Health', 'PH'),
        ('PHIL - Philosophy', 'PHIL'),
        ('PHYS - Physics', 'PHYS'),
        ('PLS - Paralegal Studies - Continuing Education', 'PLS'),
        ('PLSI - Political Science', 'PLSI'),
        ('PM - Project Management', 'PM'),
        ('PR - Project Rebound', 'PR'),
        ('PRSN - Persian', 'PRSN'),
        ('PSY - Psychology', 'PSY'),
        ('PT - Physical Therapy', 'PT'),
        ('RELS - Religious Studies', 'RELS'),
        ('RPT - Recreation, Parks And Tourism', 'RPT'),
        ('RRS - Race And Resistance Studies', 'RRS'),
        ('RUSS - Russian', 'RUSS'),
        ('S ED - Secondary Education', 'S ED'),
        ('S S - Social Science Interdisciplinary Studies', 'S S'),
        ('S W - Social Work', 'S W'),
        ('SCI - Science', 'SCI'),
        ('SLHS - Speech, Language and Hearing Sciences', 'SLHS'),
        ('SMM - Social Media Marketing', 'SMM'),
        ('SNSK - Sanskrit', 'SNSK'),
        ('SOC - Sociology', 'SOC'),
        ('SPAN - Spanish', 'SPAN'),
        ('SPED - Special Education', 'SPED'),
        ('SPMJ - Special Major', 'SPMJ'),
        ('SXS - Sexuality Studies', 'SXS'),
        ('TH A - Theatre Arts', 'TH A'),
        ('TPW - Technical And Professional Writing', 'TPW'),
        ('TURK - Turkish', 'TURK'),
        ('USP - Urban Studies And Planning', 'USP'),
        ('WGS - Women and Gender Studies', 'WGS')
    ]

class TestSFSUDepartments:
    def test_get_departments(self):
        soup = get_sample_soup()
        result = departments.get_departments(soup)
        expected = get_reference_data()
        assert result == expected

if __name__ == "__main__":
    pytest.main([__file__]) 