from .configs import DEEPSEEK_SYSTEM_PROMPT, DEEPSEEK_MODEL, DEEPSEEK_API_KEY, DEEPSEEK_BASE_URL
from data_fetchers.rmp.reviews.reviews import get_reviews, setup_request_session
from logger import logger
from openai import OpenAI
import json
import traceback
import openai
from dotenv import load_dotenv

class DeepSeekSession:
    def __init__(self):
        self.client = OpenAI(api_key=DEEPSEEK_API_KEY, base_url=DEEPSEEK_BASE_URL).chat.completions
        self.model = DEEPSEEK_MODEL
    
    def get_summary(self, reviews_data: list[dict]) -> dict:
        if not reviews_data:
            logger.warning(f"No reviews data to generate summary.")
            return None

        messages = [
            {"role": "system", "content": DEEPSEEK_SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps(reviews_data)}
        ]

        try:
            response = self.client.create(
                model=self.model,
                messages=messages,
                stream=False
            )
            result = response.choices[0].message.content
            json_result = json.loads(result)
            if self.is_valid_summary(json_result):
                return json_result
            logger.error(f"Invalid summary generated by DeepSeek: {json_result}")
            return None
        except openai.BadRequestError as e:
            return self.get_summary(reviews_data[:len(reviews_data)//2]) # Retry with half the reviews
        except Exception as e:
            logger.error(f"Failed to get summary from DeepSeek: {traceback.format_exc()}")
            return None

    def is_valid_summary(self, summary: dict) -> bool:
        if not summary.get("stats"):
            return False
        if not summary.get("stats").get("aiScore"):
            return False
        if not summary.get("stats").get("reviewCount"):
            return False
        if not isinstance(summary.get("popularTags"), list):
            return False
        for tag in summary.get("popularTags"):
            if not self.is_valid_tag(tag):
                return False
        if not summary.get("recentCourseFeedback"):
            return False
        return True

    def is_valid_tag(self, tag: dict) -> bool:
        if not tag.get("tag"):
            return False
        if not tag.get("level"):
            return False
        if not tag.get("mentions"):
            return False
    
if __name__ == "__main__":
    load_dotenv()
    deepseek_session = DeepSeekSession()
    session = setup_request_session()
    reviews = get_reviews(professor_rmp_link="professor/89065", session=session)
    summary = deepseek_session.get_summary(reviews)
    print(summary)