# /schools
SCHOOLS_KEY_SCHOOL_LIST = "schools"
SCHOOLS_KEY_BROADCASTS = "broadcasts"

SCHOOL_NAME_KEY = "schoolName"
RMP_CODE_KEY = "schoolRmpCode"
TERMS_KEY = "terms"
NOTIFICATION_KEY = "notification"
STATUS_KEY = "status"

BROADCAST_ID_KEY = "broadcastId"
BROADCAST_TEXT_KEY = "text"
BROADCAST_NEED_UPDATE_KEY = "isUpdate"
BROADCAST_MIN_VERSION_KEY = "minVersion"

MY_COLLECTION_SYNC_KEY_SCHOOL = "school"
MY_COLLECTION_SYNC_KEY_TERM = "term"
MY_COLLECTION_SYNC_KEY_DEPARTMENT = "department"
MY_COLLECTION_SYNC_KEY_PROFESSOR_NAME = "professorName"
MY_COLLECTION_SYNC_KEY_COURSE_CODE = "courseCode"
MY_COLLECTION_SYNC_KEY_CLASSES = "classes"