# /schools
SCHOOLS_KEY_SCHOOL_LIST = "schools"
SCHOOLS_KEY_BROADCASTS = "broadcasts"
SCHOOL_NAME_KEY = "schoolName"
RMP_CODE_KEY = "schoolRmpCode"
TERMS_KEY = "terms"
NOTIFICATION_KEY = "notification"
STATUS_KEY = "status"
BROADCAST_ID_KEY = "broadcastId"
TEXT_KEY = "text"
NEED_UPDATE_KEY = "isUpdate"
MIN_VERSION_KEY = "minVersion"
PLATFORM_KEY = "platform"